name: Docker

on:
  pull_request:
  push:

defaults:
  run:
    shell: bash

jobs:
  build-and-publish:
    name: Build & Publish
    runs-on: ubuntu-latest
    steps:
      - name: "Config: Image Name"
        run: echo ::set-env name=IMAGE_NAME::${{ github.repository_owner }}/$(basename ${{ github.repository }})
      - name: "Config: Registry"
        run: echo ::set-env name=REGISTRY::ghcr.io
      - name: "Repo: Checkout"
        uses: actions/checkout@v2
      - name: "Docker: Build & Publish"
        id: build
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ env.IMAGE_NAME }}
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PUBLISH_TOKEN }}
          snapshot: true
      - name: "Config: Full Image URL"
        run: echo ::set-env name=FULL_IMAGE_URL::${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.build.outputs.snapshot-tag }}
      - name: "Feedback: Commit Comment"
        uses: peter-evans/commit-comment@v1
        with:
          body: |
             :tada: **Docker testing image published**

             **URL:** ${{ env.FULL_IMAGE_URL }}

             To use the image:
             ```
             docker pull ${{ env.FULL_IMAGE_URL }}
             ```
