name: Release

on:
  release:
    types: created

jobs:
  docker-build-and-publish:
    name: "Docker: Build & Publish"
    runs-on: ubuntu-latest
    steps:
      - name: "Config: Registry"
        run: echo ::set-env name=REGISTRY::ghcr.io
      - name: "Config: Image Name"
        run: echo ::set-env name=IMAGE_NAME::${{ github.repository_owner }}/$(basename ${{ github.repository }})
      - name: "Config: Image URL"
        run: echo ::set-env name=IMAGE_URL::${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: "Repo: Checkout"
        uses: actions/checkout@v2
      - name: "Docker: Build & Publish"
        id: build
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ env.IMAGE_NAME }}
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PUBLISH_TOKEN }}
          tag_semver: true
      - name: "Config: Full Image URL"
        run: echo ::set-env name=FULL_SNAPSHOT_URL::${{ env.IMAGE_URL }}:${{ steps.build.outputs.snapshot-tag }}
